Fork jsonwebtoken until Sergio's patch lands
(Or something like it).

Rocket and jsonwebtoken depend on different versions of `cookie`, and those two
versions depend on different versions of `ring`, and `ring` has a policy of not
being linked more than once into a binary. You'll get an error like this:

```
error: multiple packages link to native library `ring-asm`, but a native library can be linked only once

package `ring v0.11.0`
    ... which is depended on by `cookie v0.9.2`
    ... which is depended on by `rocket v0.3.9`
    ... which is depended on by `changes v0.1.0 (file:///home/coleman/Code/Rust/changes)`
links to native library `ring-asm`

package `ring v0.12.1`
    ... which is depended on by `jsonwebtoken v4.0.1`
    ... which is depended on by `changes v0.1.0 (file:///home/coleman/Code/Rust/changes)`
also links to native library `ring-asm`
```

My workaround: fork `jsonwebtoken` and depend on an older `ring` that Rocket
transitively depends on, v0.11.0

Refs:
https://github.com/briansmith/ring/pull/619
https://github.com/briansmith/ring/issues/535